// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: o2o.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Outer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Either:
	//
	//	*Outer_Foo
	//	*Outer_Bar
	Either        isOuter_Either `protobuf_oneof:"either"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Outer) Reset() {
	*x = Outer{}
	mi := &file_o2o_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outer) ProtoMessage() {}

func (x *Outer) ProtoReflect() protoreflect.Message {
	mi := &file_o2o_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outer.ProtoReflect.Descriptor instead.
func (*Outer) Descriptor() ([]byte, []int) {
	return file_o2o_proto_rawDescGZIP(), []int{0}
}

func (x *Outer) GetEither() isOuter_Either {
	if x != nil {
		return x.Either
	}
	return nil
}

func (x *Outer) GetFoo() string {
	if x != nil {
		if x, ok := x.Either.(*Outer_Foo); ok {
			return x.Foo
		}
	}
	return ""
}

func (x *Outer) GetBar() string {
	if x != nil {
		if x, ok := x.Either.(*Outer_Bar); ok {
			return x.Bar
		}
	}
	return ""
}

type isOuter_Either interface {
	isOuter_Either()
}

type Outer_Foo struct {
	Foo string `protobuf:"bytes,1,opt,name=foo,proto3,oneof"`
}

type Outer_Bar struct {
	Bar string `protobuf:"bytes,2,opt,name=bar,proto3,oneof"`
}

func (*Outer_Foo) isOuter_Either() {}

func (*Outer_Bar) isOuter_Either() {}

var File_o2o_proto protoreflect.FileDescriptor

const file_o2o_proto_rawDesc = "" +
	"\n" +
	"\to2o.proto\"9\n" +
	"\x05Outer\x12\x12\n" +
	"\x03foo\x18\x01 \x01(\tH\x00R\x03foo\x12\x12\n" +
	"\x03bar\x18\x02 \x01(\tH\x00R\x03barB\b\n" +
	"\x06eitherB\x11Z\x0fo2o-deadlock/pbb\x06proto3"

var (
	file_o2o_proto_rawDescOnce sync.Once
	file_o2o_proto_rawDescData []byte
)

func file_o2o_proto_rawDescGZIP() []byte {
	file_o2o_proto_rawDescOnce.Do(func() {
		file_o2o_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_o2o_proto_rawDesc), len(file_o2o_proto_rawDesc)))
	})
	return file_o2o_proto_rawDescData
}

var file_o2o_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_o2o_proto_goTypes = []any{
	(*Outer)(nil), // 0: Outer
}
var file_o2o_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_o2o_proto_init() }
func file_o2o_proto_init() {
	if File_o2o_proto != nil {
		return
	}
	file_o2o_proto_msgTypes[0].OneofWrappers = []any{
		(*Outer_Foo)(nil),
		(*Outer_Bar)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_o2o_proto_rawDesc), len(file_o2o_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_o2o_proto_goTypes,
		DependencyIndexes: file_o2o_proto_depIdxs,
		MessageInfos:      file_o2o_proto_msgTypes,
	}.Build()
	File_o2o_proto = out.File
	file_o2o_proto_goTypes = nil
	file_o2o_proto_depIdxs = nil
}
