// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: o2o.proto

//go:build protoopaque

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Outer struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Either isOuter_Either         `protobuf_oneof:"either"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Outer) Reset() {
	*x = Outer{}
	mi := &file_o2o_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outer) ProtoMessage() {}

func (x *Outer) ProtoReflect() protoreflect.Message {
	mi := &file_o2o_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Outer) GetFoo() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Either.(*outer_Foo); ok {
			return x.Foo
		}
	}
	return ""
}

func (x *Outer) GetBar() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Either.(*outer_Bar); ok {
			return x.Bar
		}
	}
	return ""
}

func (x *Outer) SetFoo(v string) {
	x.xxx_hidden_Either = &outer_Foo{v}
}

func (x *Outer) SetBar(v string) {
	x.xxx_hidden_Either = &outer_Bar{v}
}

func (x *Outer) HasEither() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Either != nil
}

func (x *Outer) HasFoo() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Either.(*outer_Foo)
	return ok
}

func (x *Outer) HasBar() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Either.(*outer_Bar)
	return ok
}

func (x *Outer) ClearEither() {
	x.xxx_hidden_Either = nil
}

func (x *Outer) ClearFoo() {
	if _, ok := x.xxx_hidden_Either.(*outer_Foo); ok {
		x.xxx_hidden_Either = nil
	}
}

func (x *Outer) ClearBar() {
	if _, ok := x.xxx_hidden_Either.(*outer_Bar); ok {
		x.xxx_hidden_Either = nil
	}
}

const Outer_Either_not_set_case case_Outer_Either = 0
const Outer_Foo_case case_Outer_Either = 1
const Outer_Bar_case case_Outer_Either = 2

func (x *Outer) WhichEither() case_Outer_Either {
	if x == nil {
		return Outer_Either_not_set_case
	}
	switch x.xxx_hidden_Either.(type) {
	case *outer_Foo:
		return Outer_Foo_case
	case *outer_Bar:
		return Outer_Bar_case
	default:
		return Outer_Either_not_set_case
	}
}

type Outer_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Either:
	Foo *string
	Bar *string
	// -- end of xxx_hidden_Either
}

func (b0 Outer_builder) Build() *Outer {
	m0 := &Outer{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Foo != nil {
		x.xxx_hidden_Either = &outer_Foo{*b.Foo}
	}
	if b.Bar != nil {
		x.xxx_hidden_Either = &outer_Bar{*b.Bar}
	}
	return m0
}

type case_Outer_Either protoreflect.FieldNumber

func (x case_Outer_Either) String() string {
	md := file_o2o_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isOuter_Either interface {
	isOuter_Either()
}

type outer_Foo struct {
	Foo string `protobuf:"bytes,1,opt,name=foo,proto3,oneof"`
}

type outer_Bar struct {
	Bar string `protobuf:"bytes,2,opt,name=bar,proto3,oneof"`
}

func (*outer_Foo) isOuter_Either() {}

func (*outer_Bar) isOuter_Either() {}

var File_o2o_proto protoreflect.FileDescriptor

const file_o2o_proto_rawDesc = "" +
	"\n" +
	"\to2o.proto\"9\n" +
	"\x05Outer\x12\x12\n" +
	"\x03foo\x18\x01 \x01(\tH\x00R\x03foo\x12\x12\n" +
	"\x03bar\x18\x02 \x01(\tH\x00R\x03barB\b\n" +
	"\x06eitherB\x11Z\x0fo2o-deadlock/pbb\x06proto3"

var file_o2o_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_o2o_proto_goTypes = []any{
	(*Outer)(nil), // 0: Outer
}
var file_o2o_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_o2o_proto_init() }
func file_o2o_proto_init() {
	if File_o2o_proto != nil {
		return
	}
	file_o2o_proto_msgTypes[0].OneofWrappers = []any{
		(*outer_Foo)(nil),
		(*outer_Bar)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_o2o_proto_rawDesc), len(file_o2o_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_o2o_proto_goTypes,
		DependencyIndexes: file_o2o_proto_depIdxs,
		MessageInfos:      file_o2o_proto_msgTypes,
	}.Build()
	File_o2o_proto = out.File
	file_o2o_proto_goTypes = nil
	file_o2o_proto_depIdxs = nil
}
